### ISSUE TITLE
reduce deprecated warnings

### ISSUE THREAD

**Issue by eriklieben** [anseki/polyfill-svg-uri#2] opened 2016-10-11 07:45 UTC
Hi, 

Sorry to bug you again, but do you know if there is a good way to disable deprecated warnings?

![image](https://cloud.githubusercontent.com/assets/1912596/19262147/c09dc92a-8f95-11e6-95ea-01348abed027.png)

I think they occur because they exist as property and are accessed.

Could we fix this by first checking if a property exists without the webkit prefix and if so, skip it?
Then if used on an old browser it would still process the prefixed one, and on a newer browser, it would process the non-deprecated one. 

It only won't work for cases where you ignore the deprecated warning for a case where the property contains an SVG. Not sure if those exist, in my case, they don't I think but don't know about all the cases.

Or is this something that should be fixed outside of the polyfill by overriding the console.warm behavior and ignoring them?

Thanks,

Erik

**Comment by anseki** [comment] 2016-10-11 17:59
Hi @eriklieben,

You can hide those messages easily by "Filter".
If you are using Google Chrome, right-click the message and choose "Filter > Hide messages from polyfill-svg-uri.min.js".

It is correct behavior not a bug.
And the type of those messages is "Warning" not "Error".
That is, those APIs are still supported, not removed yet even if those are deprecated. And those might be still used even if the browser is new.
Therefore polyfillSvgUri should not ignore those.

Anyway, you can hide those easily if you don't want to see those.

**Comment by anseki** [comment] 2016-10-17 01:14
No reply came, and I close this issue.

**Closed as completed by anseki** 2016-10-17 01:14 UTC
